import AsyncStorage from '@react-native-async-storage/async-storage';

export type TransactionType = 'expense' | 'income';

export interface Transaction {
  id: string;
  type: TransactionType;
  amount: number;
  categoryId: string;
  date: string; // YYYY-MM-DD
  note?: string;
  recurringId?: string; // set when generated by lib/recurring.ts
}

const STORAGE_KEY = '@budgettracker/transactions';

// Serializes writes so two rapid saves (e.g. add + recurring-generation on
// the same load) can't race on AsyncStorage's read-modify-write and drop one.
let writeQueue: Promise<unknown> = Promise.resolve();
function enqueue<T>(fn: () => Promise<T>): Promise<T> {
  const result = writeQueue.then(fn);
  writeQueue = result.catch(() => {});
  return result;
}

export async function getTransactions(): Promise<Transaction[]> {
  const raw = await AsyncStorage.getItem(STORAGE_KEY);
  if (!raw) return [];
  return JSON.parse(raw) as Transaction[];
}

async function saveTransactions(transactions: Transaction[]): Promise<void> {
  await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(transactions));
}

export function addTransaction(
  data: Omit<Transaction, 'id'>
): Promise<Transaction> {
  return enqueue(async () => {
    const transactions = await getTransactions();
    const transaction: Transaction = { ...data, id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}` };
    await saveTransactions([...transactions, transaction]);
    return transaction;
  });
}

export function updateTransaction(
  id: string,
  data: Partial<Omit<Transaction, 'id'>>
): Promise<void> {
  return enqueue(async () => {
    const transactions = await getTransactions();
    const next = transactions.map((t) => (t.id === id ? { ...t, ...data } : t));
    await saveTransactions(next);
  });
}

export function deleteTransaction(id: string): Promise<void> {
  return enqueue(async () => {
    const transactions = await getTransactions();
    await saveTransactions(transactions.filter((t) => t.id !== id));
  });
}

export function transactionsForMonth(transactions: Transaction[], monthStr: string): Transaction[] {
  return transactions.filter((t) => t.date.startsWith(monthStr));
}

export interface MonthTotals {
  income: number;
  expense: number;
  net: number;
}

export function monthTotals(transactions: Transaction[], monthStr: string): MonthTotals {
  const inMonth = transactionsForMonth(transactions, monthStr);
  const income = inMonth.filter((t) => t.type === 'income').reduce((sum, t) => sum + t.amount, 0);
  const expense = inMonth.filter((t) => t.type === 'expense').reduce((sum, t) => sum + t.amount, 0);
  return { income, expense, net: income - expense };
}

export function byCategoryTotals(
  transactions: Transaction[],
  monthStr: string,
  type: TransactionType
): Record<string, number> {
  const inMonth = transactionsForMonth(transactions, monthStr).filter((t) => t.type === type);
  const totals: Record<string, number> = {};
  for (const t of inMonth) {
    totals[t.categoryId] = (totals[t.categoryId] ?? 0) + t.amount;
  }
  return totals;
}

// Generic [startDate, endDate] (both "YYYY-MM-DD", inclusive) equivalents of
// the month-scoped helpers above — added for Home's week/month/year range
// selector, which needs to total an arbitrary week or year, not just a
// month; Transactions' own List page adopted the same range selector
// 2026-08-29 and now uses transactionsInRange too (its Calendar page is
// still month-only — a day-of-month grid has no other shape — so it keeps
// using transactionsForMonth). Plain string comparison works here since
// "YYYY-MM-DD" sorts lexicographically the same as chronologically. The
// month-scoped functions above are left as-is (still what Budgets/
// demo-data/Transactions' Calendar page use) rather than rewritten atop
// these, since they're simpler for the common "just this month" case.
export function transactionsInRange(transactions: Transaction[], startDate: string, endDate: string): Transaction[] {
  return transactions.filter((t) => t.date >= startDate && t.date <= endDate);
}

export function rangeTotals(transactions: Transaction[], startDate: string, endDate: string): MonthTotals {
  const inRange = transactionsInRange(transactions, startDate, endDate);
  const income = inRange.filter((t) => t.type === 'income').reduce((sum, t) => sum + t.amount, 0);
  const expense = inRange.filter((t) => t.type === 'expense').reduce((sum, t) => sum + t.amount, 0);
  return { income, expense, net: income - expense };
}

export function byCategoryTotalsInRange(
  transactions: Transaction[],
  startDate: string,
  endDate: string,
  type: TransactionType
): Record<string, number> {
  const inRange = transactionsInRange(transactions, startDate, endDate).filter((t) => t.type === type);
  const totals: Record<string, number> = {};
  for (const t of inRange) {
    totals[t.categoryId] = (totals[t.categoryId] ?? 0) + t.amount;
  }
  return totals;
}
