import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { Pressable, StyleSheet, View } from 'react-native';

import { CategoryBadge } from '@/components/category-badge';
import { ThemedText } from '@/components/themed-text';
import { Spacing } from '@/constants/theme';
import { useCurrency } from '@/hooks/use-currency';
import { useTheme } from '@/hooks/use-theme';
import type { Category } from '@/lib/categories';
import { shortDateLabel } from '@/lib/date-range';
import type { Transaction } from '@/lib/transactions';


// A plain row, not its own card — meant to sit inside a screen's grouped-list
// container (see the `group`/`divider` styles in index.tsx/transactions.tsx).
// Redesigned 2026-08-26 (dropped the old left accent bar + arrow glyph for a
// flatter, more modern look — just a bigger icon badge and a bold colored
// amount carrying the expense/income cue) per explicit feedback that the
// previous version looked dated.
export function TransactionRow({
  transaction,
  category,
  isRecurring,
  onPress,
  showDate,
}: {
  transaction: Transaction;
  category: Category | undefined;
  // Whether transaction.recurringId points at a still-active series —
  // resolved by the caller (against lib/recurring.ts#isActiveRecurring)
  // rather than read off the transaction alone, since recurringId itself is
  // left in place forever once set (a stopped series' past transactions keep
  // it as a historical marker). Defaults to false so a caller that hasn't
  // loaded recurring data yet doesn't flash a stale badge.
  isRecurring?: boolean;
  onPress?: () => void;
  // Off by default — Transactions' own List (date-grouped under sticky
  // headers) and Calendar day-detail lists already say what date a row's in
  // via their surrounding context, so a per-row date there would just repeat
  // it. Home's recent-transactions list is the one caller that spans several
  // days at once with no such grouping, so it turns this on.
  showDate?: boolean;
}) {
  const theme = useTheme();
  const { format } = useCurrency();
  const isExpense = transaction.type === 'expense';
  // The badge keeps the category's own custom color — the expense/income cue
  // instead comes from an "Expense"/"Income" text pill paired with the amount
  // (2026-09-12, replacing a small corner dot on the icon per feedback that
  // the dot wasn't obvious enough). The pill sits in its own right-aligned
  // column above the amount rather than inline next to the category name —
  // an earlier version put it there, but on a narrow phone width it crowded
  // out the name itself (e.g. "Shopping" truncating to "Shoppi...") since the
  // name, pill, and any recurring glyph were all competing for the same
  // shrinking row. The amount text is still the standardized
  // destructive/success color too.
  const typeColor = isExpense ? theme.destructive : theme.success;
  // Manual y/m/d parse, not `new Date(transaction.date)` — the latter parses
  // "YYYY-MM-DD" as UTC midnight, which shortDateLabel's local-timezone
  // formatting can then roll back a day (same reasoning as this app's other
  // date-string handling, see CLAUDE.md).
  const [dy, dm, dd] = transaction.date.split('-').map(Number);
  const dateLabel = shortDateLabel(new Date(dy, dm - 1, dd));
  const subtitle = showDate ? (transaction.note ? `${dateLabel} · ${transaction.note}` : dateLabel) : transaction.note;

  return (
    <Pressable
      onPress={onPress}
      style={({ pressed }) => [styles.row, { backgroundColor: pressed ? theme.backgroundElement : 'transparent' }]}>
      {category && <CategoryBadge category={category} size={42} />}
      <View style={styles.middle}>
        <View style={styles.nameRow}>
          <ThemedText type="default" style={styles.categoryName} numberOfLines={1}>
            {category?.name ?? 'Other'}
          </ThemedText>
          {/* Marks a transaction generated by a still-active recurring series
              (2026-09-10; gated on isRecurring rather than a bare
              recurringId check 2026-09-12, so the badge disappears once that
              series is stopped instead of persisting on old rows forever —
              see this prop's own comment above). */}
          {isRecurring && <MaterialIcons name="event-repeat" size={14} color={theme.textTertiary} />}
        </View>
        {subtitle ? (
          <ThemedText type="small" themeColor="textSecondary" numberOfLines={1}>
            {subtitle}
          </ThemedText>
        ) : null}
      </View>
      <View style={styles.right}>
        <View style={[styles.typePill, { backgroundColor: typeColor + '1a' }]}>
          <ThemedText type="small" style={[styles.typePillText, { color: typeColor }]}>
            {isExpense ? 'Expense' : 'Income'}
          </ThemedText>
        </View>
        <ThemedText type="default" style={[styles.amount, { color: typeColor }]}>
          {(isExpense ? '-' : '+') + format(transaction.amount)}
        </ThemedText>
      </View>
      <MaterialIcons name="chevron-right" size={20} color={theme.textTertiary} />
    </Pressable>
  );
}

const styles = StyleSheet.create({
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.three,
    paddingVertical: Spacing.three,
    paddingHorizontal: Spacing.three,
  },
  middle: {
    flex: 1,
    gap: 2,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  categoryName: {
    fontWeight: '600',
    flexShrink: 1,
  },
  right: {
    alignItems: 'flex-end',
    gap: 3,
  },
  typePill: {
    paddingHorizontal: Spacing.two,
    paddingVertical: 2,
    borderRadius: Spacing.four,
  },
  typePillText: {
    fontSize: 11,
    fontWeight: '700',
  },
  amount: {
    fontVariant: ['tabular-nums'],
    fontSize: 16,
    fontWeight: '700',
  },
});
